// src/lib/components/Timetable.svelte
<script lang="ts">
  import { useTimetableEstimate } from '$lib/data/app';
  import type { StopSchedule } from '$lib/data/types';
  import { themeManager } from '$lib/managers/theme.manager.svelte';
  import buildTimetable from '$lib/utils/timetable';
  import { getRouteTint } from '$lib/utils/tints';
  import { Rss } from 'lucide-svelte';
  import { tv } from 'tailwind-variants';

  type Props = {
    schedule: StopSchedule;
    date: moment.Moment;
  };

  let { schedule, date }: Props = $props();

  const timeEstimates = useTimetableEstimate(() => ({ stop: schedule.stop, date }));
  const timetable = $derived(buildTimetable(schedule, timeEstimates.data ?? []));
  const tintColor = $derived(getRouteTint(schedule.route, themeManager.theme));

  const rowStyle = tv({
    base: 'flex items-center rounded-lg',
    variants: {
      index: {
        even: 'bg-muted',
        odd: 'bg-transparent',
      },
      highlighted: {
        true: 'bg-[var(--tint)]/25',
      },
    },
  });

  const cellStyle = tv({
    base: 'flex w-[20%] items-center justify-center rounded-md py-2',
    variants: {
      cancelled: {
        true: 'line-through',
      },
      expired: {
        true: 'text-muted-foreground',
      },
      highlighted: {
        true: 'font-bold text-[var(--tint)]',
      },
    },
  });
</script>

<div class="flex flex-col" style="--tint: {tintColor}">
  {#each timetable as row, i}
    <div
      class={rowStyle({
        index: i % 2 == 0 ? 'even' : 'odd',
        highlighted: row.highlighted,
      })}
    >
      {#each row.items as item}
        <div
          class={cellStyle({
            cancelled: item.cancelled,
            expired: item.expired,
            highlighted: item.highlighted,
          })}
        >
          <p>{item.time}</p>
          {#if item.live}
            <Rss class="mt-1 -mr-2.5 ml-0.5 size-2 self-start stroke-4" />
          {/if}
        </div>
      {/each}
    </div>
  {/each}
</div>

// src/app/components/ui/Timetable.tsx
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useTimetableEstimate } from '@lib/queries/app';
import { useTheme } from '@lib/state/utils';
import { Route, Stop, StopSchedule } from '@lib/types';
import buildTimetable from '@lib/utils/timetable';
import moment from 'moment';
import React, { useMemo } from 'react';
import { ActivityIndicator, Text, TouchableOpacity, View } from 'react-native';
import BusIcon from './BusIcon';

interface Props {
  fullSchedule: StopSchedule;
  stop: Stop;
  route: Route;
  date: moment.Moment;
  dismissBack?: () => void;
}

const Timetable: React.FC<Props> = ({
  fullSchedule,
  stop,
  route,
  date,
  dismissBack,
}) => {
  const theme = useTheme();

  const { data: estimates, isLoading } = useTimetableEstimate(
    stop,
    date || moment().toDate(),
  );

  const timetable = useMemo(() => {
    return buildTimetable(fullSchedule, estimates, theme);
  }, [fullSchedule, estimates, theme]);

  return (
    <View style={{ marginLeft: 16, paddingTop: 8 }}>
      <TouchableOpacity
        onPress={dismissBack}
        disabled={dismissBack === null}
        style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 8 }}
      >
        <BusIcon
          name={fullSchedule.route.routeCode}
          color={route.tintColor}
          style={{ marginRight: 8 }}
        />
        <View style={{ flex: 1 }}>
          <View style={{ flexDirection: 'row', alignItems: 'center' }}>
            <Text
              style={{
                fontWeight: 'bold',
                fontSize: 24,
                color: theme.text,
                flexShrink: 1,
              }}
              numberOfLines={1}
            >
              {fullSchedule.route?.name}
            </Text>
            {isLoading && <ActivityIndicator style={{ marginLeft: 8 }} />}
          </View>
          <Text style={{ color: theme.subtitle }}>
            {fullSchedule.direction.name}
          </Text>
        </View>
      </TouchableOpacity>

      <View
        style={{
          marginBottom: 8,
        }}
      >
        {timetable.map((row, rowIndex) => {
          return (
            <View
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                paddingVertical: 8,
                paddingHorizontal: 8,
                borderRadius: 8,
                backgroundColor: row.shouldHighlight
                  ? route.tintColor + '40'
                  : rowIndex % 2 === 0
                    ? theme.timetableRowB
                    : theme.timetableRowA,
              }}
              key={rowIndex}
            >
              {row.items.map((item, colIndex) => {
                return (
                  <View
                    style={{
                      flexBasis: '20%',
                      justifyContent: 'center',
                      flexDirection: 'row',
                    }}
                    key={colIndex}
                  >
                    <Text
                      style={{
                        color: item.color,
                        fontWeight:
                          item.color === route.tintColor ? 'bold' : 'normal',
                        fontSize: 16,
                        textDecorationLine: item.cancelled
                          ? 'line-through'
                          : 'none',
                      }}
                    >
                      {item.time}
                    </Text>

                    {item.live && (
                      <MaterialCommunityIcons
                        name="rss"
                        size={12}
                        color={item.color}
                        style={{
                          marginRight: -2,
                          paddingLeft: 1,
                          alignSelf: 'flex-start',
                        }}
                      />
                    )}
                  </View>
                );
              })}
            </View>
          );
        })}
        {fullSchedule.timetable.length === 0 && (
          <Text style={{ color: 'grey', textAlign: 'center' }}>
            No Timetable for Today
          </Text>
        )}
      </View>
    </View>
  );
};

export default Timetable;
